import { motion, AnimatePresence } from 'framer-motion';
import { Map, Zap, CheckCircle2, Clock, Target, AlertCircle, Printer, BookOpen, Layers } from 'lucide-react';
import { useRoadmap } from '../contexts/RoadmapContext';

export default function RoadmapBuilder() {
  const {
    topic,
    setTopic,
    duration,
    setDuration,
    customDuration,
    setCustomDuration,
    detailLevel,
    setDetailLevel,
    loading,
    error,
    roadmap,
    generateRoadmap
  } = useRoadmap();

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.15 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 30, scale: 0.95 },
    show: { opacity: 1, y: 0, scale: 1, transition: { type: 'spring' as const, bounce: 0.4 } }
  };

  return (
    <div className="min-h-[85vh] relative max-w-6xl mx-auto pb-12 print:pb-0 print:bg-white print:text-black">
      {/* Background glow - hidden on print */}
      <div className="absolute top-0 right-1/4 w-96 h-96 bg-primary/20 blur-[120px] rounded-full pointer-events-none -z-10 print:hidden" />
      <div className="absolute bottom-0 left-1/4 w-[500px] h-[500px] bg-purple-500/10 blur-[150px] rounded-full pointer-events-none -z-10 print:hidden" />

      {/* Header */}
      <motion.div 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mb-10 pt-4"
      >
        <div className="inline-flex items-center justify-center p-3 sm:p-4 rounded-2xl bg-gradient-to-br from-primary/20 to-purple-500/20 shadow-[0_0_30px_rgba(6,182,212,0.15)] mb-4 border border-white/5 print:hidden">
          <Map className="w-8 h-8 sm:w-10 sm:h-10 text-primary" />
        </div>
        <h1 className="text-3xl sm:text-5xl font-black mb-4 tracking-tight text-slate-900 dark:text-white print:text-black print:text-4xl text-left print:mb-1">
            <span className="print:hidden">AI Roadmap</span> <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-purple-500 print:text-black print:hidden">Builder</span>
            <span className="hidden print:inline text-black">Mastering {topic}</span>
        </h1>
        
        {/* For print only */}
        <div className="hidden print:block text-lg text-gray-600 font-medium text-left border-b-2 border-slate-300 pb-4 mb-6">
            Duration Aim: {duration === 'Custom' ? customDuration : duration} • Level: {detailLevel} • Generated by DevVerse
        </div>

        <p className="text-slate-600 dark:text-slate-400 max-w-2xl mx-auto text-sm sm:text-base print:hidden">
          Determine your next big technical journey. Let AI generate a highly-structured timeline, tailored to your exact pacing.
        </p>
      </motion.div>

      {/* Input Form - Hidden in Print mode! */}
      <motion.form 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        onSubmit={generateRoadmap}
        className="glass-panel p-6 sm:p-8 rounded-3xl mx-auto max-w-4xl border border-white/10 shadow-2xl relative z-10 print:hidden"
      >
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="space-y-2">
            <label className="text-sm font-bold text-slate-700 dark:text-slate-300 flex items-center gap-2">
              <Target className="w-4 h-4 text-primary"/> Goal/Topic
            </label>
            <input 
              type="text" 
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g. Machine Learning, MERN..." 
              className="w-full bg-slate-100 dark:bg-slate-900/50 border border-slate-300 dark:border-white/10 rounded-xl px-4 py-3 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all font-medium placeholder-slate-400 dark:placeholder-slate-600"
              disabled={loading}
              required
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-bold text-slate-700 dark:text-slate-300 flex items-center gap-2">
              <Layers className="w-4 h-4 text-emerald-500"/> Detail Level
            </label>
            <select
              value={detailLevel}
              onChange={(e) => setDetailLevel(e.target.value)}
              className="w-full bg-slate-100 dark:bg-slate-900/50 border border-slate-300 dark:border-white/10 rounded-xl px-4 py-3 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/50 transition-all font-medium appearance-none"
              disabled={loading}
            >
              <option value="Brief">Brief (Short & Fast)</option>
              <option value="Detailed">Detailed (In-depth tasks)</option>
            </select>
          </div>
          
          <div className="space-y-2 relative">
            <label className="text-sm font-bold text-slate-700 dark:text-slate-300 flex items-center gap-2">
              <Clock className="w-4 h-4 text-purple-400"/> Timeframe
            </label>
            <select
              value={duration}
              onChange={(e) => setDuration(e.target.value)}
              className="w-full bg-slate-100 dark:bg-slate-900/50 border border-slate-300 dark:border-white/10 rounded-xl px-4 py-3 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-purple-500/50 transition-all font-medium appearance-none"
              disabled={loading}
            >
              <option>1 Week</option>
              <option>30 Days</option>
              <option>3 Months</option>
              <option value="Custom">Custom Target...</option>
            </select>
            {duration === 'Custom' && (
              <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="absolute z-20 top-full left-0 right-0 mt-2">
                 <input
                    type="text"
                    autoFocus
                    value={customDuration}
                    onChange={(e) => setCustomDuration(e.target.value)}
                    placeholder="e.g. 1 Year, 15 Days"
                    className="w-full bg-slate-100 dark:bg-slate-800 border-2 border-purple-500/50 rounded-xl px-4 py-3 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all font-medium shadow-2xl relative"
                    required={duration === 'Custom'}
                 />
              </motion.div>
            )}
          </div>
        </div>

        <button 
          type="submit"
          disabled={loading || !topic.trim()}
          className="w-full mt-6 sm:mt-8 bg-gradient-to-r from-primary to-blue-600 hover:from-primary/90 hover:to-blue-600/90 text-white font-bold py-4 px-6 rounded-xl transition-all shadow-[0_0_20px_rgba(6,182,212,0.3)] hover:shadow-[0_0_30px_rgba(6,182,212,0.5)] active:scale-[0.98] disabled:opacity-50 disabled:pointer-events-none flex items-center justify-center gap-2 text-lg"
        >
          {loading ? (
            <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1.5, ease: "linear" }}>
              <Zap className="w-6 h-6 text-white drop-shadow-md" />
            </motion.div>
          ) : (
            <Zap className="w-5 h-5" />
          )}
          {loading ? 'Synthesizing Path...' : 'Generate Neural Sequence'}
        </button>
      </motion.form>

      {/* Error State */}
      <AnimatePresence>
        {error && (
            <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9 }}
            className="max-w-3xl mx-auto mt-6 p-4 rounded-xl bg-red-500/10 border border-red-500/30 flex items-center gap-3 text-red-500 dark:text-red-400 print:hidden"
            >
            <AlertCircle className="w-5 h-5 flex-shrink-0" />
            <p className="text-sm font-medium">{error}</p>
            </motion.div>
        )}
      </AnimatePresence>

      {/* INTERACTIVE TIMELINE RENDERING (Hidden during Print) */}
      {roadmap && !loading && (
        <motion.div 
          variants={containerVariants}
          initial="hidden"
          animate="show"
          className="max-w-5xl mx-auto mt-16 relative print:hidden"
        >
          {/* Vertical joining line */}
          <div className="absolute left-[39px] md:left-1/2 top-0 bottom-0 w-1 bg-gradient-to-b from-primary/30 via-purple-500/30 to-transparent -translate-x-1/2 rounded-full hidden md:block"></div>
          
          <div className="space-y-8 md:space-y-16">
            {roadmap.map((step, index) => {
              const isEven = index % 2 === 0;
              return (
                <motion.div 
                  key={index} 
                  variants={itemVariants}
                  className={`relative flex flex-col md:flex-row items-center gap-4 md:gap-8 ${isEven ? 'md:flex-row-reverse' : ''}`}
                >
                  {/* Timeline dot */}
                  <div className="hidden md:flex absolute left-1/2 -translate-x-1/2 w-12 h-12 rounded-full bg-[#0f111a] border-2 border-primary items-center justify-center shadow-[0_0_15px_rgba(6,182,212,0.4)] z-10">
                    <span className="text-sm font-black text-primary">{index + 1}</span>
                  </div>

                  {/* Empty space for alternating layout */}
                  <div className="hidden md:block w-1/2" />

                  {/* Content card */}
                  <div className={`w-full md:w-[calc(50%-2rem)] flex ${isEven ? 'justify-start' : 'justify-end'}`}>
                    <div className="glass-panel w-full p-6 sm:p-8 rounded-2xl border border-white/5 hover:border-primary/30 transition-colors shadow-xl relative group">
                        
                        {/* Connecting line to dot (desktop) */}
                        <div className={`hidden md:block absolute top-[40px] w-8 h-[2px] bg-primary/20 group-hover:bg-primary/50 transition-colors ${isEven ? '-left-8' : '-right-8'}`}></div>

                        <div className="inline-block px-4 py-1.5 bg-gradient-to-r from-primary/10 to-transparent rounded-lg text-xs font-bold text-primary mb-4 uppercase tracking-widest border-l-2 border-primary">
                          {step.day}
                        </div>
                        <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-3 tracking-tight">{step.title}</h3>
                        <p className="text-sm text-slate-600 dark:text-slate-400 mb-6 leading-relaxed">
                          {step.desc}
                        </p>
                        
                        <div className="space-y-3">
                            {step.tasks.map((task, tIdx) => (
                                <div key={tIdx} className="flex items-start gap-3 bg-slate-50 dark:bg-black/30 p-4 rounded-xl border border-slate-200 dark:border-white/5 hover:border-slate-300 dark:hover:border-white/10 transition-colors">
                                    <CheckCircle2 className="w-5 h-5 text-emerald-500 mt-0.5 flex-shrink-0" />
                                    <span className={`font-medium ${detailLevel === 'Brief' ? 'text-base text-slate-700 dark:text-slate-200' : 'text-sm text-slate-800 dark:text-slate-200'}`}>{task}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>

          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: roadmap.length * 0.15 + 0.5 }}
            className="text-center mt-20 pb-8"
          >
            <div className="inline-flex w-16 h-16 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 items-center justify-center shadow-[0_0_30px_rgba(16,185,129,0.3)] mb-4">
               <Target className="w-8 h-8 text-white" />
            </div>
            <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-6">Goal Reached!</h2>
            
            <div className="flex items-center justify-center gap-4">
                <button 
                   onClick={() => window.print()} 
                   className="px-6 py-4 bg-white dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-900 dark:text-white border border-slate-300 dark:border-white/10 rounded-xl transition-all font-bold flex items-center gap-3 shadow-lg group"
                >
                   <Printer className="w-5 h-5 text-primary group-hover:scale-110 transition-transform" /> Save / Print {detailLevel} PDF
                </button>
            </div>
          </motion.div>

        </motion.div>
      )}

      {/* COMPACT PRINT RENDERING (Visible only during Print) */}
      {roadmap && !loading && (
        <div className="hidden print:block max-w-4xl mx-auto">
          <div className="space-y-6">
            {roadmap.map((step, index) => (
              <div key={index} className={`border-l-4 border-slate-800 pl-6 ${detailLevel === 'Brief' ? 'pb-3' : 'pb-6'} break-inside-avoid`}>
                <div className="text-slate-500 font-bold uppercase tracking-widest text-xs mb-1">Step {index + 1} — {step.day}</div>
                <h3 className="text-2xl font-black text-black mb-2">{step.title}</h3>
                <p className="text-slate-700 mb-4">{step.desc}</p>
                
                <ul className={`space-y-3 ${detailLevel === 'Brief' ? 'mt-2' : ''}`}>
                  {step.tasks.map((task, tIdx) => (
                    <li key={tIdx} className="flex items-start gap-3">
                      <BookOpen className="w-4 h-4 text-slate-400 mt-1 flex-shrink-0" />
                      <span className="text-slate-900 leading-snug font-medium">{task}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          <div className="mt-12 pt-8 border-t border-slate-300 text-center text-slate-500 text-sm font-bold">
            Stay consistent. Powered by DevVerse Tools.
          </div>
        </div>
      )}

    </div>
  );
}
